spring:
  application:
    name: spring-security-learning

  security:
    user:
      name: pravin
      password: pravin

  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.springframework.security: WARN